[env:native]
platform = native
test_framework = custom
test_build_src = true

lib_ignore =
    FreeRTOS

build_flags =
    -Iinclude
    -Itest/mocks

build_src_filter =
    +<temperature_alarm.cpp>
    +<navigation.cpp>