[platformio]
default_envs = bluepill_f103c8


; ============================================================
; STM32 BLUE PILL / WOKWI
; ============================================================

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube

monitor_speed = 115200
build_type = debug

build_flags =
    -Iinclude
    -Ilib/FreeRTOS/include
    -Ilib/FreeRTOS/portable/GCC/ARM_CM3

lib_archive = no


; ============================================================
; NATIVE UNIT TESTS
; ============================================================

[env:native]
platform = native

test_framework = custom
test_build_src = true

build_flags =
    -Iinclude
    -Itest/mocks

build_src_filter =
    +<temperature_alarm.cpp>
    +<navigation.cpp>

lib_ignore =
    FreeRTOS